source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'


target 'BaseFramework' do
    use_frameworks!
#    pod 'RxSwift'           # RxSwift的必备库
#    pod 'RxCocoa'           # 对UIKit Foundation进行Rx化
#    pod 'RxDataSources'     # 帮助我们优雅的使用tableView的数据源方法
#    pod 'Moya/RxSwift'      # 为RxSwift专用提供，对Alamofire进行封装的一个网络请求库


    pod 'GuidePageView'
    pod 'Kingfisher'        # 加载网络图片，类似SDWebImage
    pod 'SwiftyJSON'        # json解析
    pod 'ObjectMapper'      # json解析
    pod 'SnapKit'           # UI布局（类似Masonry）
    pod 'Moya'              # 网络请求封装
    pod 'CryptoSwift'       # 加密库（MD5、SHA、AES...）
    pod 'HandyJSON',:git => 'https://github.com/alibaba/HandyJSON.git', :branch => 'dev_for_swift5.0'
    pod 'FWCycleScrollView' #轮播组件
    
    pod 'YCShadowView'    #UIView阴影

    pod 'MJRefresh'
    pod 'SVProgressHUD'
end
